#!/usr/bin/env bash
# This script displays a list of currently running processes in a user-oriented with a processes hierarchy.

top -b -n 1 -H | head -1 && ps -e --forest -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command

