#!/usr/bin/env bash

# Creating the PID file
echo $$ > /var/run/myscript.pid

# Function to handle signals
HANDLE_SIGNAL(){
	case "$1" in SIGQUIT)
		rm -f /var/run/myscript.pid
		exit 0
		;;
	esac
}
# Trap signals
trap 'echo "Removing PID file and terminating..."' SIGQUIT
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y u no love me?!"' SIGINT

# Main loop
while true; do
	echo "To infinity and beyond"
	sleep 2
done

