#!/usr/bin/env bash

# Creating the PID file
echo $$ > /var/run/myscript.pid

# Function to handle signals
HANDLE_SIGNAL(){
	case "$1" in
		SIGQUIT)
		rm -f /var/run/myscript.pid
		exit 0
		;;
	SIGTERM)
		echo "I hate the kill command"
		rm -f /var/run/myscript.pid
		exit 0
		;;
	SIGINT)
		echo "Y u no love me?!"
		;;

	esac
}
# Trap signals
trap 'HANDLE_SIGNAL SIGQUIT' SIGQUIT
trap 'HANDLE_SIGNAL SIGTERM' SIGTERM
trap 'HANDLE_SIGNAL SIGINT' SIGINT

# Main loop
while true; do
	echo "To infinity and beyond"
	sleep 2
done

