#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash.

for pid in /proc/[0-9]*; do
    if [[ -d "$pid" ]]; then
        cmd=$(<"$pid/comm")
        if [[ "$cmd" == *bash* ]]; then
            echo "$(basename "$pid") $cmd"
        fi
    fi
done
