#!/usr/bin/env bash
# This script displays the PID, along with the process name, of processes whose name contain the word bash.

#ps -Ao pid,comm | awk '/[b]ash/' 
ps -eo pid,comm | awk '/[b]ash/ {printf("%d\tbash\n", $1)}'

