#!/usr/bin/env bash
# This script will stops 4-to_infinity_and_beyond process.

# Find the PID of the process
PID=$(pgrep -f '4-to_infinity_and_beyond')

# Kill the process
if [ -n "$PID" ];
then
	kill "$PID"
fi

