#!/usr/bin/env bash
# This script will stops 4-to_infinity_and_beyond process.


#Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "100-process_and_pid_file")

#Kill the process
if [ -n "$pid" ];
then
	kill -9 "$pid"
fi

