#!/usr/bin/env bash
# This script will displays To infinity and beyond indefinitely and sleep 2 between each iteration but when receiving a SIGTERM signal will displays I am invincible.

# Trap the SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

#Loop indefinitely
while true;
do
	echo "To infinity and beyond";
	sleep 2;
done

