#!/usr/bin/env bash
# script that writes "I am alive!" to the file /tmp/my_process indefinitely amdn pause every 2 seconds.

touch /tmp/my_process
while true
do
	echo "I am live!" >> /tmp/my_process;
	sleep 2;
done
