#!/usr/bin/env bash
#this script that configures an Ubuntu server with the below requirements

#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts /etc/hosts_backup

sed -i '/localhost/d' /etc/hosts_backup
echo "127.0.0.2 localhost" >> /etc/hosts_backup
echo "8.8.8.8 facebook.com" >> /etc/hosts_backup
cp /etc/hosts_backup /etc/hosts
